apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-test-2
  namespace: temporal
spec:
  replicas: 25
  selector:
    matchLabels:
      app: temporal-test
  template:
    metadata:
      labels:
        app: temporal-test
    spec:
      containers:
        - name: your-app
          image: qadiludmer/temporal-test:latest
          imagePullPolicy: Always
          command: ["poetry"]
          args: ["run", "worker"]
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal-frontend:7233
          resources:
            requests:
              cpu: "10"
              memory: "10Gi"

